Feature/cleaning dataset
mgarciafernandez-altran/boston-crime-mediavilla pull request #1
Opened 2021-03-22 09:35 UTC by javiermediavilla

Primer intento de pull request

2021-03-22 09:38 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
>  Created on Wed Mar 17 09:43:28 2021
Test comentario

2021-03-22 09:39 UTC, javiermediavilla commented on DatasetCleaning.py
>  Created on Wed Mar 17 09:43:28 2021
No estoy deacuerdo

2021-03-22 09:40 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
>  Created on Wed Mar 17 09:43:28 2021
Vale haz lo que quieras

2021-03-22 09:41 UTC, mgarciafernandez-altran commented
Esto esta todo mal

2021-03-22 09:48 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +#### Packages ####
General rules about importing libraries and packages at Python:
1.- Never ever do `import X as Y`
2.- `import X` is preferred over `from X import Y`
3.- Libraries shall be dividen on three grous ordered: standard libraries, thrid party libraries, custom libraries.
4.- inside each group libraries shall be in alphabetical order

2021-03-22 09:48 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> -El objetivo de este stript de Python es generar una versión preprocesada del dataset.
Comments always in English

2021-03-22 09:51 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +######################################
General comment on every file. If the file is intended to be 'executable', that is run with `python file.py` or even `./file.py` it MUST have defined a main function `def main()` and a `if __name__ == '__main__':` sencetence

2021-03-22 09:54 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +for ii in range(len(data_numpy)):
Give meaningful names to all the variables, even if it is an index. In general, indexes have a functional name for example, if it is a flight id, even though it is an integer, shall be named something like `flight_id`. If it is something meaningless like the index of the list shall be named like that `list_index`.

2021-03-22 09:55 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +slot_sort             = np.sort(slot)
In general we follow the PEP-8 rules. This means that lines below shall be something like `unique_slots = len...`. That is the symbol `=` shall be enclosed between single blank spaces

2021-03-22 09:57 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +x_train, x_test, y_train, y_test = train_test_split(data_X_shuffle, data_Y_shuffle, test_size=0.25, random_state=4)
As a rule, une must ALWAYS state the name of the arguments of functions when calling them, for example, `train_test_split(data_X_shuffle...` shall be `train_test_split(name_of_var=data_X...`

2021-03-22 10:08 UTC, mgarciafernandez-altran requested changes

2021-03-22 10:08 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> -# -*- coding: utf-8 -*-
This first line of comment is junk added by IDE. It means nothing

2021-03-22 10:08 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +The main objetive of the script is to generate a preprocessed version o the dataset 'crimes_dataset.csv'
Main comment of file shall be more descriptive

2021-03-22 10:08 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +data   = data.applymap(lambda s: mymap.get(s) if s in mymap else s)
To not use the `lambda` directive. It complicates code review by external people and in general leads to bad programming practices. it is demonstrated that `lambda` sencences my be converted to more pythonic sentences or even to specific functions

2021-03-22 10:08 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +#### Load the data from csv ####
In general on this script I miss more modularity There is no single function!!!

2021-03-22 10:08 UTC, mgarciafernandez-altran commented on DatasetCleaning.py
> +    word_time      = str(data['YEAR'][ii]) + str(data['MONTH'][ii]) + str(data['DAY_OF_WEEK'][ii]) + str(data['DAY_OF_THE_MONTH'][ii])
Do not use string contatenation! Use f-strings!! (see python official documentation)

2021-03-23 13:02 UTC, mgarciafernandez-altran approved these changes

2021-03-23 13:02 UTC, merged