Feature/analytics
mgarciafernandez-altran/boston-crime-mediavilla pull request #3
Opened 2021-03-23 16:43 UTC by javiermediavilla

Random Forest training

2021-03-23 16:51 UTC, mgarciafernandez-altran requested changes

2021-03-23 16:51 UTC, mgarciafernandez-altran commented on Analytics.py
> +    RF_model = sklearn.ensemble.RandomForestRegressor(n_estimators=n_estimators,max_depth=max_depth,criterion=criterion)
variables shall be all lowercase this shall be named `rf_model`

2021-03-23 16:51 UTC, mgarciafernandez-altran commented on Analytics.py
> +######### Modificable Variables #########
There shall not be 'hard codded variables at any Python code. These are envirionment variables. Please read them from an external coniguration file, like a YAML

2021-03-23 16:51 UTC, mgarciafernandez-altran commented on Analytics.py
> +    RF_model = trainer_RandomForest(x_train=x_train,
let the variable be lowercase `rf_model`

2021-03-23 16:51 UTC, mgarciafernandez-altran commented on Analytics.py
> +def trainer_RandomForest(x_train : numpy.ndarray, x_test : numpy.ndarray, y_train : numpy.ndarray, y_test : numpy.ndarray, n_estimators : int, max_depth : int, criterion : str, visualization : bool)
function shall be named lowercase `trainer_randomforest`

2021-03-23 16:51 UTC, mgarciafernandez-altran commented on Analytics.py
> +def save_model_method(RF_model : sklearn.ensemble.RandomForestRegressor, save_model : bool) -> None:
here `rf_model` is an argument and shall be also lowercase

2021-03-24 12:09 UTC, javiermediavilla commented
All changes done.

2021-03-24 12:11 UTC, javiermediavilla commented
DONE

2021-03-24 12:11 UTC, closed without merging